# Generated by Django 5.1.4 on 2024-12-24 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ClassroomHandler', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teaching',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teaching',
            name='teaching_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching', to='ClassroomHandler.classroom'),
        ),
        migrations.AlterUniqueTogether(
            name='teaching',
            unique_together={('teaching_class', 'teacher')},
        ),
    ]
