# Generated by Django 5.1.4 on 2024-12-27 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassroomHandler', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentClassroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_classroom', to='ClassroomHandler.classroom')),
            ],
        ),
    ]
