# Generated by Django 5.1.4 on 2025-01-19 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClassroomHandler', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='announcement_title',
        ),
    ]
