# Generated by Django 5.1.4 on 2025-01-01 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClassroomHandler', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='teacher',
            new_name='instructor',
        ),
    ]
