# Generated by Django 5.1.4 on 2025-01-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassroomHandler', '0003_rename_teacher_classroom_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='cover_image',
            field=models.ImageField(default='classroom_covers/default-covers.jpg', upload_to='classroom_covers/'),
        ),
    ]
