# Generated by Django 5.1.4 on 2025-01-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserHandler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='classroom_count',
            field=models.IntegerField(default=0),
        ),
    ]
