# Generated by Django 5.1.4 on 2024-12-27 18:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ClassroomHandler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField()),
                ('question_fullmarks', models.FloatField()),
                ('question', models.TextField(max_length=500)),
                ('question_image', models.ImageField(upload_to='exam_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('exam_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exam_title', models.CharField(max_length=300)),
                ('instructions', models.TextField(max_length=600)),
                ('starting_time', models.DateTimeField()),
                ('ending_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='ClassroomHandler.classroom')),
            ],
            options={
                'ordering': ['ending_time', 'starting_time', 'duration'],
            },
        ),
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='ExamHandler.examination')),
            ],
        ),
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ExamHandler.question')),
                ('options', models.TextField(max_length=500)),
                ('answer', models.CharField(max_length=10)),
            ],
            bases=('ExamHandler.question',),
        ),
        migrations.CreateModel(
            name='Written',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ExamHandler.question')),
                ('answer_sheet', models.FileField(upload_to='documents/')),
            ],
            bases=('ExamHandler.question',),
        ),
        migrations.AddField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='ExamHandler.examination'),
        ),
    ]
