# Generated by Django 5.1.4 on 2025-01-11 19:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ClassroomHandler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField(null=True)),
                ('question_fullmarks', models.FloatField()),
                ('question', models.TextField(max_length=500)),
                ('question_image', models.ImageField(upload_to='exam_question_images/')),
            ],
        ),
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ExamHandler.question')),
                ('options', models.JSONField(blank=True, null=True)),
                ('answer', models.CharField(max_length=10)),
            ],
            bases=('ExamHandler.question',),
        ),
        migrations.CreateModel(
            name='Written',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ExamHandler.question')),
                ('answer_sheet', models.FileField(upload_to='exam_answer_documents/')),
            ],
            bases=('ExamHandler.question',),
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('exam_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exam_title', models.CharField(max_length=300)),
                ('instructions', models.TextField(max_length=600)),
                ('starting_time', models.DateTimeField()),
                ('ending_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='ClassroomHandler.classroom')),
                ('mcq_questions', models.ManyToManyField(related_name='mcq_questions', to='ExamHandler.mcq')),
                ('written_questions', models.ManyToManyField(related_name='written_questions', to='ExamHandler.written')),
            ],
            options={
                'ordering': ['ending_time', 'starting_time', 'duration'],
            },
        ),
    ]
